routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware('auth')->group(function () {
    Route::resource( 'pages','PageController');
    Route::resource( 'posts','PostController');
    Route::resource( 'categories','CategoryController');
});



Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{content}', 'PageController@pagetype');

Route::get('/search/autocomplete', 'SearchController@autocomplete');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!

                    <a class="button is-primary" href="{{route('pages.index')}}">Nouvelle page</a>
                    <a class="button is-primary" href="{{route('posts.index')}}">Nouveau post</a>
                    <a class="button is-primary" href="{{route('categories.index')}}">Nouvelle categorie</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection