routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware('auth')->group(function () {
    Route::resource( 'pages','PageController');
    Route::resource( 'posts','PostController');
    Route::resource( 'categories','CategoryController');
});



Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{content}', 'PageController@pagetype');

Route::get('/search/autocomplete', 'SearchController@autocomplete');

resources/views/page/create.blade.php
@extends('layouts.app')

@section('content')


    <form action="{{route('pages.store')}}" method="POST" id="demo-form">
        {{ csrf_field() }}
    <div class="field">
        <label class="label">Nom de la page</label>
        <p class="control">
            <input class="input" type="text" placeholder="Nom de la page" name="nom">
        </p>
    </div>



    <div class="field">
        <label class="label">Sujet</label>
        <p class="control">
            <input class="input" id="q" type="text" placeholder="Chercher" name="sujet">
        </p>
    </div>

    <div class="field">
        <label class="label">Contenu</label>
        <p class="control">
            <textarea id="my-editor" name="content" class="form-control">{!! old('content', 'test editor content') !!}</textarea>
        </p>
    </div>



    <div class="field is-grouped">
        <p class="control">
                <button class="button is-primary g-recaptcha" type="submit" data-sitekey="6LeJvycUAAAAADO6jyeJ8jO-aHRqlcdbIPJSoM6u" data-callback='onSubmit'>Envoyer</button>
        </p>
        <p class="control">
            <button class="button is-link" type="reset">Annuler</button>
        </p>
    </div>

    </form>

@endsection

resources/views/page/edit.blade.php
@extends('layouts.app')

@section('content')


    <form action="{{route('pages.update', $page->id)}}" method="POST" id="demo-form">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PATCH">
        <div class="field">
            <label class="label">Nom du post</label>
            <p class="control">
                <input class="input" type="text" placeholder="Text input" name="nom"  value="{{ $page->title }}{{ old('nom') }}">
            </p>
        </div>



        <div class="field">
            <label class="label">Sujet</label>
            <p class="control">
                <input class="input" id="q" type="text" placeholder="Chercher" name="sujet" value="{{ $page->subject }}{{ old('sujet') }}">
            </p>
        </div>

        <div class="field">
            <label class="label">Contenu</label>
            <p class="control">
                <textarea id="my-editor" name="content" class="form-control" value="{{ $page->content }}{{ old('content') }}">{!!$page->content !!}</textarea>
            </p>
        </div>



        <div class="field is-grouped">
            <p class="control">
                <button class="button is-primary g-recaptcha" type="submit" data-sitekey="6LeJvycUAAAAADO6jyeJ8jO-aHRqlcdbIPJSoM6u" data-callback='onSubmit'>Envoyer</button>
            </p>
            <p class="control">
                <button class="button is-link" type="reset">Annuler</button>
            </p>
        </div>

    </form>

@endsection

resources/views/page/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Les pages</h1>

        <a class="button is-primary" href="{{ route('pages.create') }}">Nouvelle</a>

        <!-- will be used to show any messages -->
        @if (Session::has('message'))
            <div class="notification">{{ Session::get('message') }}</div>
        @endif

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <td>ID</td>
                <td>Titre</td>
                <td>Sujet</td>
                <td>Actions</td>
            </tr>
            </thead>
            <tbody>
            @foreach($pages as $key => $value)
                <tr>
                    <td>{{ $value->id }}</td>
                    <td>{{ $value->title }}</td>
                    <td>{{ $value->subject }}</td>

                    <!-- we will also add show, edit, and delete buttons -->
                    <td>

                        <!-- delete the nerd (uses the destroy method DESTROY /nerds/{id} -->
                        <!-- we will add this later since its a little more complicated than the other two buttons -->

                        <!-- show the nerd (uses the show method found at GET /nerds/{id} -->
                        <a class="button" href="{{ URL::to('pages/' . $value->id) }}">Afficher</a>

                        <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->
                        <a class="button" href="{{ URL::to('pages/' . $value->id . '/edit') }}">Editer</a>
                        <a data-method="delete"
                           data-token="{{csrf_token()}}" data-confirm="Are you sure?"
                           class="button" href="{{ URL::to('pages/' . $value->id ) }}">Supprimer</a>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/page/indextype.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="title is-1 tag tagpage">{{$type}}</h1>
        <!-- will be used to show any messages -->
        @if (Session::has('message'))
            <div class="alert alert-info">{{ Session::get('message') }}</div>
        @endif
        @foreach($pages as $key => $value)
        <div class="content">
            {!! $value->content !!}
        </div>
        @endforeach

<?php $clef = 0; ?>

            @foreach($posts as $key => $value)


            <?php $string = str_slug($value->title);?>



                @if($clef % 3 == 0)
                <div class="tile is-ancestor">
                    @endif

                <div class="tile is-parent">
                    <article class="tile is-child box">
                        <p class="title"><a href="{{$value->subject}}/{{$string}}">{{$value->title}}</a> </p>
                        <p >{!! \Illuminate\Support\Str::words($value->content, 100) !!}</p>
                    </article>
                </div>

                    @if($clef % 3 == 2)
                </div>
                            @endif
            <?php $clef++; ?>
            @endforeach

    </div>
@endsection

resources/views/page/show.blade.php
@extends('layouts.app')

@section('content')

    <nav class="breadcrumb">
        <ul>
            <li><a>  {{ config('app.name', 'Laravel') }}</a></li>
            <li><a>{{ $lapage->subject }}</a></li>
        </ul>
    </nav>


    <h1 class="title is-1">{{ $lapage->title }}</h1>

<div class="jumbotron text-center">
    <p>
       {!! $lapage->content !!}<br>
    </p>
</div>


@endsection