routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware('auth')->group(function () {
    Route::resource( 'pages','PageController');
    Route::resource( 'posts','PostController');
    Route::resource( 'categories','CategoryController');
});



Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{content}', 'PageController@pagetype');

Route::get('/search/autocomplete', 'SearchController@autocomplete');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [ 'nom', 'sujet', 'content'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $itemsPerPage = 10;
        $categorys = Category::orderBy('created_at', 'desc')->paginate($itemsPerPage);
        return view('category.index')->with('categorys', $categorys);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create', array('title' => 'Add News'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $id = Auth::id();
        DB::table('categories')->insert(
            ['title' => $request->nom, 'slug'=> str_slug($request->nom), 'author_id' => $id ]
        );
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param \App\Page $page
     */
    public function show($id)
    {
        // get the nerd
        $lapage = Category::findOrFail($id);

        // show the view and pass the nerd to it
        return view('category.show', compact('lapage') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id )
    {
        $category = Category::findOrFail($id);
        $input = $request->all();
        DB::table('categories')
            ->where('id', $id)
            ->update(['title' => $request->nom, 'subject' => $request->sujet,  'content' => $request->content]);
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        $page = Category::findOrFail($id);
        $page->delete();

        // redirect
        session()->flash('message', 'Nous avons bien supprimé la catégorie');
        return redirect(route('categories.index'));
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')


    <form action="{{route('categories.store')}}" method="POST" id="demo-form">
        {{ csrf_field() }}
    <div class="field">
        <label class="label">Nom de la catégorie</label>
        <p class="control">
            <input class="input" type="text" placeholder="Nom de la catégorie" name="nom">
        </p>
    </div>



    <div class="field is-grouped">
        <p class="control">
                <button class="button is-primary g-recaptcha" type="submit" data-sitekey="6LeJvycUAAAAADO6jyeJ8jO-aHRqlcdbIPJSoM6u" data-callback='onSubmit'>Envoyer</button>
        </p>
        <p class="control">
            <button class="button is-link" type="reset">Annuler</button>
        </p>
    </div>

    </form>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')


    <form action="{{route('pages.update', $page->id)}}" method="POST" id="demo-form">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PATCH">
        <div class="field">
            <label class="label">Nom du post</label>
            <p class="control">
                <input class="input" type="text" placeholder="Text input" name="nom"  value="{{ $page->title }}{{ old('nom') }}">
            </p>
        </div>



        <div class="field">
            <label class="label">Sujet</label>
            <p class="control">
                <input class="input" id="q" type="text" placeholder="Chercher" name="sujet" value="{{ $page->subject }}{{ old('sujet') }}">
            </p>
        </div>

        <div class="field">
            <label class="label">Contenu</label>
            <p class="control">
                <textarea id="my-editor" name="content" class="form-control" value="{{ $page->content }}{{ old('content') }}">{!!$page->content !!}</textarea>
            </p>
        </div>



        <div class="field is-grouped">
            <p class="control">
                <button class="button is-primary g-recaptcha" type="submit" data-sitekey="6LeJvycUAAAAADO6jyeJ8jO-aHRqlcdbIPJSoM6u" data-callback='onSubmit'>Envoyer</button>
            </p>
            <p class="control">
                <button class="button is-link" type="reset">Annuler</button>
            </p>
        </div>

    </form>

@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Les categories</h1>

        <a class="button" href="{{ route('categories.create') }}">Nouveau</a>

        <!-- will be used to show any messages -->
        @if (Session::has('message'))
            <div class="notification">{{ Session::get('message') }}</div>
        @endif

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <td>ID</td>
                <td>Titre</td>
                <td>Sujet</td>
                <td>Actions</td>
            </tr>
            </thead>
            <tbody>
            @foreach($categorys as $key => $value)
                <tr>
                    <td>{{ $value->id }}</td>
                    <td>{{ $value->title }}</td>
                    <td>{{ $value->subject }}</td>

                    <!-- we will also add show, edit, and delete buttons -->
                    <td>

                        <!-- delete the nerd (uses the destroy method DESTROY /nerds/{id} -->
                        <!-- we will add this later since its a little more complicated than the other two buttons -->

                        <!-- show the nerd (uses the show method found at GET /nerds/{id} -->
                        <a class="button" href="{{ URL::to('categories/' . $value->id) }}">Afficher</a>

                        <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->
                        <a class="button" href="{{ URL::to('categories/' . $value->id . '/edit') }}">Editer</a>
                        <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->
                        <a data-method="delete"
                           data-token="{{csrf_token()}}" data-confirm="Are you sure?"
                           class="button" href="{{ URL::to('categories/' . $value->id ) }}">Supprimer</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')

    <nav class="breadcrumb">
        <ul>
            <li><a>  {{ config('app.name', 'Laravel') }}</a></li>
            <li><a>{{ $lapage->subject }}</a></li>
        </ul>
    </nav>


    <h1 class="title is-1">{{ $lapage->title }}</h1>

<div class="jumbotron text-center">
    <p>
       {!! $lapage->content !!}<br>
    </p>
</div>


@endsection